#!/usr/bin/env bash
# assemble-review-package.sh
# Assemble a cross-tool review package for an external reviewer model
# (Codex / GPT-5 / Gemini / ...) via human copy-paste.
#
# The package is three concatenated sections, in order:
#   1. Reviewer prompt body (extracted from docs/prompts/ANALYSIS_PROMPT_PLAYBOOK_EXTERNAL_REVIEW.md)
#   2. Handoff Header for this round (supplied by caller)
#   3. The document under review (full markdown, including frontmatter)
#
# See docs/PLAYBOOK_CROSS_TOOL_REVIEW_LOOP.md for the full workflow.
#
# Usage:
#   bash scripts/assemble-review-package.sh <round> <doc-path> <handoff-path> [out-path]
#
# Arguments:
#   round         Review round number (e.g. 1, 2).
#   doc-path      Repo-relative path to the document under review
#                 (e.g. docs/PLAYBOOK_CROSS_TOOL_REVIEW_LOOP.md).
#   handoff-path  Path to the Handoff Header markdown file for this round
#                 (typically under /tmp, generated by Claude each round).
#   out-path      Optional output path.
#                 Default: /tmp/codex-review-round-<round>.txt

set -euo pipefail

if [ $# -lt 3 ]; then
    cat >&2 <<USAGE
Usage: $0 <round> <doc-path> <handoff-path> [out-path]
  round         Review round number (e.g. 1).
  doc-path      Repo-relative path to the document under review.
  handoff-path  Path to the handoff markdown file for this round.
  out-path      Optional output path (default: /tmp/codex-review-round-<round>.txt).
USAGE
    exit 2
fi

ROUND="$1"
DOC_REL="$2"
HANDOFF="$3"
OUT="${4:-/tmp/codex-review-round-${ROUND}.txt}"

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROMPT_FILE="$REPO_ROOT/docs/prompts/ANALYSIS_PROMPT_PLAYBOOK_EXTERNAL_REVIEW.md"
DOC_FILE="$REPO_ROOT/$DOC_REL"

if [ ! -f "$PROMPT_FILE" ]; then
    echo "ERROR: reviewer prompt not found at docs/prompts/ANALYSIS_PROMPT_PLAYBOOK_EXTERNAL_REVIEW.md" >&2
    exit 1
fi
if [ ! -f "$DOC_FILE" ]; then
    echo "ERROR: document not found: $DOC_REL" >&2
    exit 1
fi
if [ ! -f "$HANDOFF" ]; then
    echo "ERROR: handoff file not found: $HANDOFF" >&2
    exit 1
fi

if ! grep -q "Review Handoff" "$HANDOFF"; then
    echo "WARN: '$HANDOFF' does not contain 'Review Handoff' — is this the right file?" >&2
fi

{
    awk '/^========== BEGIN REVIEWER PROMPT ==========$/ {flag=1; next}
         /^========== END REVIEWER PROMPT ==========$/   {flag=0}
         flag' "$PROMPT_FILE"
    echo ""
    cat "$HANDOFF"
    echo ""
    echo "---"
    echo ""
    cat "$DOC_FILE"
} > "$OUT"

LINES=$(wc -l < "$OUT")

cat <<SUMMARY
Review package assembled.
  Round:    $ROUND
  Document: $DOC_REL
  Handoff:  $HANDOFF
  Output:   $OUT ($LINES lines)

Next step:
  Open $OUT, select all, copy, paste into the reviewer chat, send.
SUMMARY
